{% set name = "tb3py" %}
{% set version = "2021.11.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tb3py-{{ version }}.tar.gz
  sha256: f6aad4083177e783ff23224c63fe4085e3f9972e31a718a12293a4ca740d3997

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - requests >=2.26.0
  run:
    - jarvis-tools
    - julia >=0.5.6
    - numpy >=1.19.5
    - pytest
    - python >=3.6
    - requests >=2.26.0

test:
  imports:
    - tb3py
    - tb3py.tests


about:
  home: https://github.com/usnistgov/tb3py
  summary: 'tb3: an open-source software package for accurate and efficient electronic structure calculations using tight-binding (TB), including three-body interactions. https://pages.nist.gov/ThreeBodyTB.jl'
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - knc6
